# -*- coding: utf-8 -*-
"""СпецГлМат_ДЗ2_МышеловаПолинаСергеевна.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zexuE1LzR1lCvshl4blmh9Mqmq8apvV
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv('/content/drive/MyDrive/Superstore Sales Dataset.csv')

data.head()

data.shape

data['Customer ID'].nunique()

data = data[['Customer ID', 'Order Date', 'Sales']]
data.head()

data['Order Date'].astype

# приведем признак 'Order Date' к формату даты
data['Order Date'] = pd.to_datetime(data['Order Date'])
data['Order Date'].head()

# оставим только год и месяц
data['Order Date'] = data['Order Date'].apply(lambda x: x.strftime('%Y-%m'))

# добавим признак 'First order' дату первого заказа клиента
data.set_index('Customer ID', inplace=True)
data['First order'] = data.groupby(level=0)['Order Date'].min()
data.reset_index(inplace=True)
data.insert(len(data.columns), 'Total orders', 0, allow_duplicates=False)
data.head()

cohorts = data.groupby(['First order', 'Order Date']).agg({'Customer ID': pd.Series.nunique,
'Total orders': pd.Series.count, 'Sales': np.sum})
cohorts.rename(columns={'Customer ID': 'Number of users'}, inplace=True)
cohorts.tail()

def cohort_period(data):
    data['CohortPeriod'] = np.arange(len(data)) + 1
    return data

cohorts = cohorts.groupby(level=0).apply(cohort_period)
cohorts.head(10)

cohorts.reset_index(inplace=True)
cohorts.set_index(['CohortPeriod', 'First order'], inplace=True)
cohort_group_size = cohorts['Number of users'].groupby(level=1).first()
cohort_group_size.head()

cohorts['Number of users'].unstack(1).head(15)

cohorts.reset_index(inplace=True)
cohorts.set_index(['First order', 'CohortPeriod'], inplace=True)
cohort_group_size = cohorts['Number of users'].groupby(level=0).first()
cohorts['Number of users'].unstack(0)
user_retention = cohorts['Number of users'].unstack(0).divide(cohort_group_size, axis=1)

sns.set(style='ticks')
plt.figure(figsize=(40, 20))
plt.title('Cohorts: User Retention')
sns.heatmap(user_retention.T, mask=user_retention.T.isnull(), annot=True, fmt='.0%', cmap='Blues')

"""### Исходя из построенной тепловой карты можно сделать следующие выводы:

1)	В большинстве случаев Retention rate значительно падает уже на второй месяц после первой даты заказа, что говорит о том, что клиенты совершают покупки нерегулярно. Следовательно, есть смысл делать акцент рекламной кампании на новых клиентов.

2)	Во второй половине отчетного периода Retention rate сохраняет стабильные показатели вплоть до 12 месяца после совершения первой покупки. Приведенные данные можно использовать как оценку эффективности проведенных маркетинговых активностей, повлиявшие на удержание клиентов.

3)	Интересными являются когорты 2017–02, 2017–8, 2017–10, сохраняющие Retention rate на уровне 50%. Стоит обратить внимание на клиентов, которые совершали покупки в данные периоды и предложить им особые условия для их дальнейшего удержания.

4)	Стоит разобрать отдельные случаи повышенного показателя, например на 21 месяц для 2016–07 или на 14 месяц для 2016–10, чтобы разобраться, чем мотивирован такой скачок.

"""